; Firmware brazo planar 2GDL con motorreductores DC + encoder (GM25-370)
; Plataforma fijada a espressif32 6.x => Arduino-ESP32 2.0.x (API LEDC clasica:
; ledcSetup/ledcAttachPin). No actualizar a Arduino 3.x antes de la entrega.

[env:nodemcu-32s]
platform = espressif32@6.9.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -Wall
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    madhephaestus/ESP32Encoder@0.11.7
